---
 
- hosts: all
  become: true
  tasks:
 
  - name: install apache php htop neofetch
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
        - "{{ htop_package }}"
        - "{{ neofetch_package }}"
      state: latest
      update_cache: yes
